### ISSUE TITLE
error on MIS REPORT STYLES. Odoo 11+e

### ISSUE THREAD

**Issue by ulisesgamboa** [OCA/mis-builder#126]
I had installed the MIS Builder with DEMO and I fouknd this error on MIS REPORT STYLES. Could you help me please?   

Regards

Error:
Uncaught Error: QWeb2: Template 'FieldColor' not found

http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:3689
Rastreo de error:
Error: QWeb2: Template 'FieldColor' not found
    at Object.exception (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:3689:7)
    at Engine._render (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:3734:103)
    at Engine.render (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:3730:151)
    at Class.renderElement (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:3949:1078)
    at Array.<anonymous> (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:3949:917)
    at Array.<anonymous> (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:802:681)
    at fire (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:796:299)
    at Object.add [as done] (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:797:467)
    at Array.<anonymous> (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:802:649)
    at Function.each (http://172.25.33.250:8069/web/content/580-df8dab6/web.assets_common.js:625:767)

**Comment by sbidoul** [comment]
Have you installed then web_widget_color module?

**Comment by ulisesgamboa** [comment]
Yes, I had installed… thanks for your prompt response
![image](https://user-images.githubusercontent.com/33880229/45703232-4631d100-bb39-11e8-96d7-ff4ad258a10e.png)

**Comment by sbidoul** [comment]
Hm, that's strange. I think web_widget_color has been rewritten recently. Perhaps that created an incompatibility.

**Comment by sbidoul** [comment]
Can you explain the steps to reproduce the error?

**Comment by pedrobaeza** [comment]
Maybe he hadn't restarted service or refreshed browser.

**Comment by ulisesgamboa** [comment]
Yes, I had download the web_widget_color and all dependencies like "report_xlsx" and "date_range" from Odoo's app page. The MIS Builder from GitHub, install all and to try the functionality appear this error.

**Comment by ulisesgamboa** [comment]
>           Maybe he hadn't restarted service or refreshed browser.

Yes, I restarted Odoo's service, the explorer not but I had tried and now is working.

Thanks for you help
