### ISSUE TITLE
Error when click the commitment amount

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#185]
I found error when I click the commitment amount in the MIS Reports as follow :

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 904, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 926, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/odoo12/odoo/odoo/models.py", line 4560, in search_read
    result = records.read(fields)
  File "/opt/odoo12/odoo/odoo/models.py", line 2765, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo12/odoo/odoo/models.py", line 2918, in _read_from_database
    values = [convert(value, target, validate=False) for value in values]
  File "/opt/odoo12/odoo/odoo/models.py", line 2918, in <listcomp>
    values = [convert(value, target, validate=False) for value in values]
  File "/opt/odoo12/odoo/odoo/fields.py", line 1623, in convert_to_cache
    raise TypeError("%s (field %s) must be string or date, not datetime." % (value, self))
TypeError: 2019-04-30 14:12:05 (field mis.committed.purchase.date) must be string or date, not datetime.

**Comment by sbidoul** [comment]
Can you please provide exact steps to reproduce the issue? Ideally reproducible on runbot.

**Comment by hitrosol** [comment]
I have run the runbot, 
http://3367845-12-0-7d694b.runbot2.odoo-community.org/web?debug=1#id=1&active_id=1&model=mis.report.instance&view_type=form&menu_id=90

I paste the screen shoot here, I added another "nice to have" things in the template report as well.
![image](https://user-images.githubusercontent.com/5949936/56975109-4d729000-6b9a-11e9-8b39-9888d41b10fa.png)

After I click that amount, the error shows like this:

![image](https://user-images.githubusercontent.com/5949936/56975247-9591b280-6b9a-11e9-902b-5b5ddfb94388.png)

**Comment by sbidoul** [comment]
Thanks. This bug seems specific to v12. It would help if you could confirm it works fine in v11.

**Comment by hitrosol** [comment]
It's working in v11. 

The budget amount in detail account is also good to have so the user will know how much the budget especially if we have more than 1 accounts in line category. 
Thanks to address my concern.

**Comment by sbidoul** [comment]
Thanks for the confirmation for v11. Please open one issue per topic.

**Comment by sbidoul** [comment]
This problem seems to be specific to the demo module. The sql view should truncate to get the date part of datetime fields.

**Comment by sbidoul** [comment]
Fixed, thanks for reporting.

**Comment by hitrosol** [comment]
Thanks to solve this issue. Hopefully this addons will be more comprehensive as possible.
