### ISSUE TITLE
[v13] Error with budget by account

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#276]
Here is the report I have created:

![screenshot-localhost_8069-2020 04 (2)](https://user-images.githubusercontent.com/5735158/79345912-04922380-7f32-11ea-8758-85d39a66d9db.png)

I get the following error with I add on my P&L report a comparison with a budget by account.

https://drive.google.com/open?id=1v57-UuUj6Z3f0xBu6LVu1NThzBjscp3Y

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/src/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/src/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/src/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/src/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/src/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/src/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/src/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/src/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 806, in compute
    kpi_matrix = self._compute_matrix()
  File "/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 799, in _compute_matrix
    self._add_column(aep, kpi_matrix, period, period.name, description)
  File "/odoo/external-src/mis-builder/mis_builder_budget/models/mis_report_instance.py", line 81, in _add_column
    aep, kpi_matrix, period, label, description
  File "/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 743, in _add_column_move_lines
    no_auto_expand_accounts=self.no_auto_expand_accounts,
  File "/odoo/external-src/mis-builder/mis_builder/models/mis_report.py", line 887, in _declare_and_compute_period
    expression_evaluator.aep_do_queries()
  File "/odoo/external-src/mis-builder/mis_builder/models/expression_evaluator.py", line 37, in aep_do_queries
    self.aml_model,
  File "/odoo/external-src/mis-builder/mis_builder/models/aep.py", line 353, in do_queries
    lazy=False,
  File "/odoo/external-src/mis-builder/mis_builder/models/prorata_read_group_mixin.py", line 90, in read_group
    lazy=lazy,
  File "/odoo/src/odoo/models.py", line 2140, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/odoo/src/odoo/models.py", line 2183, in _read_group_raw
    for fspec in fields:
TypeError: 'module' object is not iterable

**Comment by sbidoul** [comment]
@fclementic2c can you try with #277 ?

That's a stupid bug indeed. I think it's triggered because you have `bale` in your expressions and that's normally not used for a P&L (only balp). That's why I had not seen that during testing. So you triggered the code path that skips the pro-rata temporis adjustments of budgeted amounts.

**Comment by sbidoul** [comment]
Fixed in #277
