### ISSUE TITLE
[v13] error when adding % diff Act vs Budget

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#297]
When I try to add a column Diff in % I get an error :
see video
https://drive.google.com/open?id=1KW61djDL6VXk1QBDoz8NUECrSYAOE0of

error:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/src/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/src/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/src/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/src/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/src/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/src/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/src/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/src/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 806, in compute
    kpi_matrix = self._compute_matrix()
  File "/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 800, in _compute_matrix
    kpi_matrix.compute_comparisons()
  File "/odoo/external-src/mis-builder/mis_builder/models/kpimatrix.py", line 314, in compute_comparisons
    common_subkpis = self._common_subkpis([col, base_col])
  File "/odoo/external-src/mis-builder/mis_builder/models/kpimatrix.py", line 298, in _common_subkpis
    common_subkpis = set(cols[0].subkpis)
AttributeError: 'NoneType' object has no attribute 'subkpis'

**Comment by miquelalzanillas** [comment]
Same here. When trying to compare two columns in v11. Is this a bug?
