### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by Ashu-jun** [OCA/mis-builder#324]
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_
run
    self.check(display_num_errors=True)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_uniq
ue
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Lenovo\PycharmProjects\learn\logmonitor (1)\logmonitor\urls.py", line 24, in <module>
    url(r'openid/', include('djangooidc.urls')),
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\djangooidc\urls.py", line 5, in <module>
    from . import views
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\djangooidc\views.py", line 20, in <module>
    CLIENTS = OIDCClients(settings)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\djangooidc\oidc.py", line 188, in __init__
    self.client[key] = self.create_client(**val)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\djangooidc\oidc.py", line 216, in create_client
    behaviour=kwargs["behaviour"], verify_ssl=verify_ssl, **args)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\djangooidc\oidc.py", line 32, in __init__
    client_authn_method, keyjar, verify_ssl)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\oic\oic\__init__.py", line 335, in __init__
    config=config, client_cert=client_cert)
  File "C:\Users\Lenovo\PycharmProjects\learn\venv\lib\site-packages\oic\oauth2\__init__.py", line 212, in __init__
    self.issuer = self.config['issuer']
TypeError: 'bool' object is not subscriptable

**Comment by sbidoul** [comment]
@Ashu-jun this stack trace does not seems to be related to this repo in any way. So closing.
