### ISSUE TITLE
Error MIS BUILDER in odoo 16 (Docker)

### ISSUE THREAD

**Issue by madco001** [OCA/mis-builder#590]
Hello good,
I downloaded and installed the community version of Odoo version 16, I installed the MIS Builder from the odoo app store, it installs, but when I go to generate a report it gives me the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/mis_builder/models/mis_report_instance.py", line 876, in compute
    kpi_matrix = self._compute_matrix()
  File "/mnt/extra-addons/mis_builder/models/mis_report_instance.py", line 869, in _compute_matrix
    self._add_column(aep, kpi_matrix, period, period.name, description)
  File "/mnt/extra-addons/mis_builder/models/mis_report_instance.py", line 832, in _add_column
    return self._add_column_move_lines(
  File "/mnt/extra-addons/mis_builder/models/mis_report_instance.py", line 801, in _add_column_move_lines
    self.report_id._declare_and_compute_period(
  File "/mnt/extra-addons/mis_builder/models/mis_report.py", line 897, in _declare_and_compute_period
    self._declare_and_compute_col(
  File "/mnt/extra-addons/mis_builder/models/mis_report.py", line 754, in _declare_and_compute_col
    kpi_matrix.set_values(kpi, col_key, vals, drilldown_args)
  File "/mnt/extra-addons/mis_builder/models/kpimatrix.py", line 213, in set_values
    self.set_values_detail_account(
  File "/mnt/extra-addons/mis_builder/models/kpimatrix.py", line 237, in set_values_detail_account
    for val, drilldown_arg, subcol in zip(
TypeError: zip() takes no keyword arguments

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://0.0.0.0:8069/web/assets/163-4b50a63/web.assets_backend.min.js:988:163)
    at XMLHttpRequest.<anonymous> (http://0.0.0.0:8069/web/assets/163-4b50a63/web.assets_backend.min.js:996:13)

**Comment by fgarcia-humanoide** [comment]
I have the same problem in last installations of odoo 16. It seems that you must have python 3.10 installed, but the oficial odoo doker compose installs python 3.9 . I do not know how to change python version in a container.

**Comment by pedrobaeza** [comment]
@sbidoul Can you remove such `zip` keyword argument that makes it incompatible with Python 3.9?

**Comment by sbidoul** [comment]
I'll be happy to review and merge a PR that does this. But keep in mind that OCA does not support Python 3.9 for Odoo 16, since CI runs on Python 3.10, as well as runboat.

**Comment by pedrobaeza** [comment]
It seems that the official Odoo Docker for 16 is running on Python 3.9, according the reports in https://www.aeodoo.org/forum/general-1/16-mis-builder-en-su-ultima-version-es-incompatible-con-el-docker-oficial-de-odoo-869

**Comment by sbidoul** [comment]
> It seems that the official Odoo Docker for 16 is running on Python 3.9,

I know but the decision to build and test 16.0 on 3.10 has been taken more than one year ago so we are not going to change now.

**Comment by pedrobaeza** [comment]
OK, I'm not discussing that, just that this incompatible keyword argument can be fixed. As I was not the one introducing it, I don't know right now what to touch, and I'm not affected either, as Doodba is using Python 3.10 as well.

**Comment by anhvu-sg** [comment]
Hi, I cannot upgrade Docker 16.0 to Python 3.10 due to many reasons (need to recheck all the compatibility of Python 3.10 with OCA modules + custom modules).

Therefore, I am using the source code from this commit (https://github.com/OCA/mis-builder/commit/280c9c9c) for my clients.

If anyone has a better idea, please let us know.
