### ISSUE TITLE
Error when uninstall mis_builder

### ISSUE THREAD

**Issue by pydooactiva** [OCA/mis-builder#603]
## Module
mis_builder

## Describe the bug
When i tried to uninstall the module in Odoo15 Enterprise (Odoo.sh)  i have the following ERROR and database appear "Internal error server" and im not beaing able to access any more to my database. 
<img width="1029" alt="Captura de pantalla 2024-03-06 a la(s) 18 34 15" src="https://github.com/OCA/mis-builder/assets/125298354/ae1f1755-86fa-47e8-affd-336a1867806e">

The error log is as follows
024-03-06 21:16:47,729 4 ERROR XXXXXXXXXXX werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._generate_asset_nodes_cache at 0x7fcdd07584c0>, 'web.assets_backend', True, False, '', False, False, False, (None, 'es_ES'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._get_asset_content at 0x7fcdd0758790>, 'web.assets_backend', None, False, False, (None, 'es_ES'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 221, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_205>", line 152, in template_205
    
  File "<template_205>", line 135, in t_call_content
    
  File "<template_205>", line 39, in qweb_t_set__t_t_t_1_
    
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 246, in _get_asset_nodes
    return self._generate_asset_nodes_cache(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
  File "<decorator-gen-71>", line 2, in _generate_asset_nodes_cache
    
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 255, in _generate_asset_nodes_cache
    return self._generate_asset_nodes(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 263, in _generate_asset_nodes
    files, remains = self._get_asset_content(bundle, nodeAttrs, defer_load=defer_load, lazy_load=lazy_load)
  File "<decorator-gen-72>", line 2, in _get_asset_content
    
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 274, in _get_asset_content
    asset_paths = self.env['ir.asset']._get_asset_paths(bundle=bundle, css=True, js=True)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 124, in _get_asset_paths
    self._fill_asset_paths(bundle, addons, installed, css, js, xml, asset_paths, [])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 223, in _fill_asset_paths
    process_path(asset.directive, asset.target, asset.path)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 178, in process_path
    addon, paths = self._get_paths(path_def, installed, exts)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 324, in _get_paths
    raise Exception("Unallowed to fetch files from addon %s" % addon)
Exception: Unallowed to fetch files from addon mis_builder

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 815, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in checked_call
    result.flatten()
  File "/home/odoo/src/odoo/odoo/http.py", line 1284, in flatten
    self.response.append(self.render())
  File "/home/odoo/src/odoo/odoo/http.py", line 1277, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1994, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 435, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 2002, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/home/odoo/src/enterprise/web_studio/models/ir_qweb.py", line 47, in _render
    return super(IrQWeb, self)._render(template, values=values, **options)
  File "/home/odoo/src/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 225, in render_template
    raise QWebException("Error when render the template", self, options,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/odoo/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/server.py", line 482, in app
    return self.app(e, s)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 110, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/home/odoo/.local/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1348, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1314, in __call__
    return self.app(environ, start_wrapped)
  File "/home/odoo/.local/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1541, in dispatch
    result = ir_http._dispatch()
  File "/home/odoo/src/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 198, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 616, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 759, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: Unallowed to fetch files from addon mis_builder
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._generate_asset_nodes_cache at 0x7fcdd07584c0>, 'web.assets_backend', True, False, '', False, False, False, (None, 'es_ES'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._get_asset_content at 0x7fcdd0758790>, 'web.assets_backend', None, False, False, (None, 'es_ES'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 221, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_205>", line 152, in template_205
  File "<template_205>", line 135, in t_call_content
  File "<template_205>", line 39, in qweb_t_set__t_t_t_1_
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 246, in _get_asset_nodes
    return self._generate_asset_nodes_cache(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
  File "<decorator-gen-71>", line 2, in _generate_asset_nodes_cache
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 255, in _generate_asset_nodes_cache
    return self._generate_asset_nodes(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 263, in _generate_asset_nodes
    files, remains = self._get_asset_content(bundle, nodeAttrs, defer_load=defer_load, lazy_load=lazy_load)
  File "<decorator-gen-72>", line 2, in _get_asset_content
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 274, in _get_asset_content
    asset_paths = self.env['ir.asset']._get_asset_paths(bundle=bundle, css=True, js=True)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 124, in _get_asset_paths
    self._fill_asset_paths(bundle, addons, installed, css, js, xml, asset_paths, [])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 223, in _fill_asset_paths
    process_path(asset.directive, asset.target, asset.path)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 178, in process_path
    addon, paths = self._get_paths(path_def, installed, exts)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_asset.py", line 324, in _get_paths
    raise Exception("Unallowed to fetch files from addon %s" % addon)
Exception: Unallowed to fetch files from addon mis_builder

Error when render the template
Exception: Unallowed to fetch files from addon mis_builder
Template: 205
Path: /t/t/t[1]/t[2]
Node: <t t-call-assets="web.assets_backend" t-js="false"/> - - -

## To Reproduce
Uninstall mis_builder in Odoo 15 Enterprise Odoo.sh

**Comment by pydooactiva** [comment]
@JordiBForgeFlow @pedrobaeza @lmignon @Martronic-SA can help me with this?

**Comment by pydooactiva** [comment]
Do you have any idea how to solve it?
